version: "3.8"
services:
  db:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
      - MYSQL_DATABASE=$MYSQL_NAME
      - MYSQL_USER=$MYSQL_USER
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - db:/var/lib/mysql
  disney-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file: ./.env
    ports:
      - $PORT:3000
    environment:
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_NAME=$MYSQL_NAME
      - MYSQL_PASS=$MYSQL_PASS
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_HOST=$MYSQL_HOST
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
volumes:
  db:
